# Generated by Django 5.0.3 on 2024-04-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmember',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='boardmember',
            name='middle_name',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
