# Generated by Django 5.0.3 on 2024-03-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_cgpa_customuser_face_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='face_data',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='finger_data',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='live_camera_photo',
            field=models.ImageField(blank=True, null=True, upload_to='live_camera_photos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
