# Generated by Django 5.0.3 on 2024-05-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_admincandidatecreation_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincandidatecreation',
            name='first_name',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admincandidatecreation',
            name='last_name',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admincandidatecreation',
            name='middle_name',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
    ]
