# Generated by Django 5.0.3 on 2024-04-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_phone_boardmember_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admincandidatecreationform',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='admincandidatecreationform',
            name='middle_name',
            field=models.CharField(default=34, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admincandidatecreationform',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='admincandidatecreationform',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admincandidatecreationform',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
