# Generated by Django 5.0.3 on 2024-04-24 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_phone_admincandidatecreationform_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='admin',
            field=models.OneToOneField(default=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
