# Generated by Django 5.0.3 on 2024-05-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_admincandidatecreation_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincandidatecreation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admincandidatecreation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admincandidatecreation',
            name='middle_name',
        ),
    ]
