# Generated by Django 5.0.3 on 2024-03-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_face_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='live_camera_photo',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Voter')], default=2),
        ),
    ]
