# Generated by Django 5.0.3 on 2024-04-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_boardmember_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='middle_name',
        ),
    ]
