# Generated by Django 5.0.3 on 2024-05-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_admincandidatecreation_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincandidatecreation',
            name='admin',
        ),
        migrations.AddField(
            model_name='admincandidatecreation',
            name='first_name',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admincandidatecreation',
            name='last_name',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admincandidatecreation',
            name='middle_name',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
    ]
