# Generated by Django 5.0.3 on 2024-05-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_admincandidatecreation_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincandidatecreation',
            name='password',
            field=models.CharField(default=100, max_length=128),
            preserve_default=False,
        ),
    ]
