# Generated by Django 5.0.3 on 2024-04-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_admincandidatecreation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincandidatecreation',
            name='photo',
            field=models.ImageField(default=100, upload_to='Candidate_Photo/'),
            preserve_default=False,
        ),
    ]
