# Generated by Django 5.0.3 on 2024-05-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_id',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
