# Generated by Django 5.0.3 on 2024-05-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_face_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='face_id',
        ),
    ]
