# Generated by Django 5.0.4 on 2024-04-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='job',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
