# Generated by Django 5.0.3 on 2024-05-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(max_length=50)),
                ('start_time', models.TimeField(max_length=50)),
                ('end_date', models.DateField(max_length=50)),
                ('end_time', models.TimeField(max_length=50)),
                ('is_posted', models.BooleanField(default=False, verbose_name='Posted')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isposted', models.BooleanField(default=False, verbose_name='isPosted')),
            ],
        ),
        migrations.CreateModel(
            name='NominationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(max_length=50)),
                ('start_time', models.TimeField(max_length=50)),
                ('end_date', models.DateField(max_length=50)),
                ('end_time', models.TimeField(max_length=50)),
                ('is_posted', models.BooleanField(default=False, verbose_name='Posted')),
            ],
        ),
    ]
