# Generated by Django 5.0.3 on 2024-04-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationpost',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='Posted'),
        ),
    ]
