# Generated by Django 5.0.3 on 2024-05-11 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionpost',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electionpost',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominationpost',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominationpost',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electionpost',
            name='end_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='electionpost',
            name='end_time',
            field=models.TimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nominationpost',
            name='end_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nominationpost',
            name='end_time',
            field=models.TimeField(max_length=50),
        ),
    ]
