# Generated by Django 5.0.3 on 2024-04-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_member', '0002_nominationpost_is_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('is_posted', models.BooleanField(default=False, verbose_name='Posted')),
            ],
        ),
    ]
