# Generated by Django 5.0.3 on 2024-05-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
