# Generated by Django 5.0.3 on 2024-04-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
