# Generated by Django 5.0.3 on 2024-05-19 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_candidate_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='voter',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='voting.voter'),
            preserve_default=False,
        ),
    ]
