# Generated by Django 5.0.3 on 2024-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_nominee'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='position',
            field=models.CharField(choices=[('President', 'President')], default='President', max_length=50),
        ),
    ]
