# Generated by Django 5.0.3 on 2024-04-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_nominee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='name',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
