# Generated by Django 5.0.3 on 2024-05-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_nominee_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominee',
            name='voter',
        ),
    ]
