# Generated by Django 5.0.3 on 2024-04-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_Nominee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominee',
            name='name',
        ),
    ]
