# Generated by Django 5.0.3 on 2024-04-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_Nominee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary')], default='President', max_length=50),
        ),
    ]
