# Generated by Django 5.0.3 on 2024-04-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_nominee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='is_approved',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='position',
            field=models.CharField(choices=[('President', 'President')], default='President', max_length=50),
        ),
    ]
