# Generated by Django 5.0.3 on 2024-04-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_nominee_is_approved_alter_nominee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
