# Generated by Django 5.0.3 on 2024-04-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_nominee_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
