# Generated by Django 5.0.3 on 2024-05-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_alter_nominee_position_alter_votes_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='position',
            field=models.CharField(choices=[('President', 'President')], default='President', max_length=50),
        ),
    ]
