# Generated by Django 5.0.3 on 2024-05-11 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_alter_nominee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.position'),
        ),
    ]
