# Generated by Django 5.0.3 on 2024-05-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_alter_nominee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominee',
            name='position',
        ),
    ]
