# Generated by Django 5.0.3 on 2024-05-11 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_remove_nominee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='position',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='voting.position'),
            preserve_default=False,
        ),
    ]
