# Generated by Django 5.0.3 on 2024-05-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_nominee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='position',
            field=models.CharField(choices=[('President', 'President')], default='President', max_length=50),
        ),
    ]
