# Generated by Django 5.0.3 on 2024-05-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0018_alter_nominee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='candidate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='votes',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
