# Generated by Django 4.1.12 on 2024-03-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cgpa', models.FloatField()),
                ('face_data', models.CharField(max_length=100)),
                # ('finger_data', models.CharField(max_length=100)),
            ],
        ),
    ]
