# Generated by Django 5.0.3 on 2024-03-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardMember',
        ),
    ]
