# Generated by Django 5.0.3 on 2024-04-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
    ]
