# Generated by Django 5.0.3 on 2024-04-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_auto_20240424_1611'),
    ]

    operations = [
    ]
