# Generated by Django 5.0.3 on 2024-04-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
