# Generated by Django 5.0.3 on 2024-04-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmessage',
            name='me',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
