# Generated by Django 5.0.3 on 2024-04-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_campaignmessage_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignmessage',
            name='me',
        ),
    ]
